#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# checking if the number of parameters is less than 4
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# performing the file transfer using scp
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
