#!/usr/bin/env bash
# Bash script that displays content of the current directory in list format

for file in *
do
	if [ -f "$file" ]; then
		filename=$(basename "$file")
		second_field=$(echo "$filename" | cut -d '-' -f 2)
		echo "$second_field"
	fi
done
