#!/usr/bin/env bash
# Bash script that creates an RSA key pair.

#Defining key file names
private_key="school"
public_key="${private_key}.pub"

#checking if the key files already exist
if [[ -e "$private_key" || -e "$public_key" ]]; then
	echo "Key files already exist. Aborting."
	exit 1
fi

# creating RSA key pair with the paraphrase
ssh-keygen -t rsa -b 4096 -f "$private_key" -N "betty"

